### PR TITLE
Applied gradle checkstyle plugin and fixed a redundant import

### PR DESCRIPTION
**Pull request by CoXier**

### CODE REVIEW

**Comment by drakeet** [comment]
Great! Thank you very much.

**Comment by drakeet** [comment]
Link to #3

**Comment by drakeet** [comment]
For removing the redundant import `java.util.Objects` and the `java.util.Objects` is added since JDK 1.7, we should release a new version later.

**Comment by drakeet** [comment]
Merged. BTW, maybe we can turn to use the https://github.com/novoda/gradle-static-analysis-plugin for the _checkstyle_ and _findbugs_.

**Comment by CoXier** [comment]
Another awesome plugin. But I think if we need `PWD` and `findbugs` too, we can add them by ourselves because `gradle-static-analysis-plugin` itself maybe have issue.

**Comment by drakeet** [comment]
Well. We are already using _findbugs_ and _Idea Analyze_, but do not use _PWD_. And we can apply _findbugs_ through gradle plugin as well next time.

**Pull request merged**
